### ISSUE TITLE
Separate supplemental and annual tax bill

### ISSUE THREAD

**Issue by rgbkrk** [typpo/ca-property-tax#12]
In Santa Cruz County I'm seeing some instances of the stated number possibly being the supplemental tax bill rather than the annual + the supplemental:

![image](https://user-images.githubusercontent.com/836375/97188040-4eb95480-1760-11eb-8878-5ec60ac984b7.png)

![image](https://user-images.githubusercontent.com/836375/97188079-5aa51680-1760-11eb-85d5-cd1239f12b0c.png)

**Comment by typpo** [comment]
Resolved now https://officialdata.org/ca-property-tax/#36.9597861601903,-121.99121184647083,20

**Comment by rgbkrk** [comment]
Thanks!
